version: 2
jobs:
  job_build_and_deploy:
    working_directory: ~/project
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: Show current branch and commit hash
          command: echo ${CIRCLE_BRANCH} ${CIRCLE_SHA1}
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run:
          name: Install local dependencies
          command: npm install
      - run:
          name: Rebuild node-sass
          command: npm rebuild node-sass
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          name: Linting
          command: npm run lint
      - run:
          name: Unit testing
          command: npm run test:ci
      - run:
          name: End-to-end testing
          command: npm run e2e:ci
      - run:
          name: Building
          command: npm run build:ssr
      - add_ssh_keys:
          fingerprints:
            - "53:26:ff:6a:83:ee:fb:a6:c3:e1:9a:f1:c8:b8:6b:ee"
      - run:
          name: Deploying
          command: npm run deployment

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - job_build_and_deploy